# genereal {
    # lock_cmd = pidof hyprlock || hyprlock
# }
listener {
    timeout = 300
    on-timeout = hyprlock
}
listener {
    timeout = 60                                # 2.5min.
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}